aparApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.DashboardHome.as_view(), name='DashboardHome'),
    path('create/', views.CreateApar.as_view(), name='createapar'),
    path('update/<int:pk>', views.UpdateApar.as_view(), name='updateapar'),
    path('scan/', views.ScanMenu.as_view(), name='scanmenu'),
    path('scan/<slug:slug>', views.ScanMenu.as_view(), name='scanmenu'),
    path('cek/', views.CekApar.as_view(), name='cekapar'),
    path('cek/<slug:slug>', views.CekAparById.as_view(), name='cekapar'),
    path('history/', views.CekAparList.as_view(), name='cekhistory'),
    path('detail/', views.DetailApar.as_view(), name='detailapar'),
    path('detail/<slug:slug>', views.DetailApar.as_view(), name='detailapar'),
    path('', views.Scanner.as_view(), name='scanner'),
    #path('scan/', views.ScanMenu.as_view(), name='scanmenu'),
    path('login/', views.AparLoginView.as_view(), name='login'),
    path('logout/', views.AparLogoutView.as_view(), name='logout'),
]

aparManager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aparApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aparApp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_resized import ResizedImageField
from django.contrib.auth.models import User

class Apar(models.Model):
    nomor = models.IntegerField()
    lokasi = models.CharField(max_length=100)
    jenis = models.CharField(max_length=16)
    ukuran = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    expired = models.DateField(blank=True, null=True)
    tanggal_periksa = models.DateField(blank=True, null=True)
    path_foto = ResizedImageField(size=[280, 390],upload_to='images/%Y%m',default='images/202304/apar.jpg')
    path_QR = models.CharField(max_length=1024, null=True)
    slug = models.SlugField(null=True)

    def __str__(self):
        return str(self.nomor) + " - " +  self.lokasi
    
    def get_absolute_url(self):
        return reverse('updateapar', args=[str(self.id)])

class Pemeriksaan(models.Model):
    STATUS_CHOICES = (
    (True, 'OK'),
    (False, 'Tidak OK' )
    )
    #class Status(models.TextChoices):
    #    OK = 'OK',_('OK')
    #    NOT_OK = 'Not OK',_('Not OK')

    apar = models.ForeignKey(Apar, on_delete=models.CASCADE)
    tekanan = models.BooleanField(choices=STATUS_CHOICES, default=False)
    tabung = models.BooleanField(choices=STATUS_CHOICES, default=False)
    pin = models.BooleanField(choices=STATUS_CHOICES, default=False)
    handle = models.BooleanField(choices=STATUS_CHOICES, default=False)
    label = models.BooleanField(choices=STATUS_CHOICES, default=False)
    selang = models.BooleanField(choices=STATUS_CHOICES, default=False)
    tanggal = models.DateField(auto_now_add=True, blank=True, null=True)
    sign = models.BooleanField(choices=STATUS_CHOICES, default=False)
    keterangan = models.CharField(max_length=300, blank=True, null=True)
    path_foto = ResizedImageField(size=[280, 390],upload_to='images/%Y%m',default='images/202304/apar.jpg')
    pemeriksa = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.tanggal) + "-" + str(self.apar)

    def get_absolute_url(self):
        return reverse('scanmenu', args=[str(self.apar.slug)])
        #return reverse('DashboardHome')
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.apar.tanggal_periksa = self.tanggal
        self.apar.path_foto = self.path_foto
        self.apar.save()

templates/apar_createview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    
</div>
<br>
<div class="container shadow px-4 p-4">
    <h2>Input Data APAR {{ object.nomor }}</h2>
    <div class="row">
        <div class="col p-3 text-center">
            <img src="{{ object.path_foto.url }}" alt="Foto APAR" max-width="100%" width="280px" height="390px" class="rounded">
        </div>
        <div class="col p-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-borderless">
                    <thead>
                    
                    </thead>
                    <tbody>
                        {% for field in form %}
                        <tr>
                            <td>
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% if field.field.required %}
                                    <span class="required">*</span>
                                {% endif %}
                            </td>
                            <td>
                                {{ field }}
                                {% if field.help_text %}
                                    <br><small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                                {% if field.name == 'path_QR' and form.path_QR.value %}
                                    <img src="{{ MEDIA_URL }}/media/images/qrcodes/{{ object.path_QR }}.png" alt="{{ form.path_QR.value }}" width="34">
                                {% endif %}
                            </td>
                          </tr>
                          {% if field.errors %}
                            <tr>
                              <td></td>
                              <td>
                                <div class="alert alert-danger">
                                  {% for error in field.errors %}
                                    <p>{{ error }}</p>
                                  {% endfor %}
                                </div>
                              </td>
                            </tr>
                          {% endif %}
                        {% endfor %}
                    </tbody>
                    <tr>
                        <th>
                           
                        </th>
                        <td class="text-end">
                            <button type="submit" class="btn btn-success">Save</button>
                            <a href="{% url 'DashboardHome' %}"  class="btn btn-danger">Cancel</a>
                        </td>
                    </tr>
                </table>
            
        </div>
        
        </form>
    </div>
</div>
<script>
    let nomor_apar = document.getElementById('id_nomor').value;
    function isiQR(){
        nomor_apar = document.getElementById('id_nomor').value;
        document.getElementById('id_path_QR').value = 'fln-apar-' + nomor_apar;
    }
    function isiSlug(){
        document.getElementById('id_slug').value = 'fln-apar-' + nomor_apar;
    }
</script>
{% endblock content %}

templates/apar_detailview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    
</div>
<br>
<div class="container shadow px-4 p-4">
    <h2>Detail Data APAR {{ object.nomor }}</h2>
    <div class="row">
        <div class="col p-3 text-center">
            <img src="{{ object.path_foto.url }}" max-width="100%" width="280px" height="390px" class="rounded">
        </div>
        <div class="col p-3">
            <form method="POST" enctype="multipart/form-data">
                <table class="table table-borderless">
                    <thead>
                    
                    </thead>
                    <tbody>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">Nomor APAR</label></td>
                            <td>{{ object.nomor }}</td>
                        </tr>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">Lokasi</label></td>
                            <td>{{ object.lokasi}}</td>
                        </tr>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">Jenis</label></td>
                            <td>{{ object.jenis }}</td>
                        </tr>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">Ukuran</label></td>
                            <td>{{ object.ukuran }} Kg</td>
                        </tr>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">Tanggal Expired</label></td>
                            <td>{{ object.expired }}</td>
                        </tr>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">Pemeriksaan Terakhir</label></td>
                            <td>{{ object.tanggal_periksa }}</td>
                        </tr>
                        <tr>
                            <td><label for="{{ field.id_for_label }}">QR</label></td>
                            <td><img src="{{ MEDIA_URL }}/media/images/qrcodes/{{ object.path_QR }}.png" width="34"></td>
                        </tr>
                    </tbody>
                    <tr>
                        <th>
                           
                        </th>
                        <td class="text-end">
                            <a href="{% url 'DashboardHome' %}"  class="btn btn-danger">Back</a>
                        </td>
                    </tr>
                </table>
            
        </div>
        
        </form>
    </div>
    <div class="row p-3">
        <h4>History Pemeriksaan</h4>
        <div class="table-responsive">
            <table class="table table-sm table-danger table-striped table-bordered text-center w-auto">
                <tr>
                    <thead>
                        <td>Tanggal</td>
                        <td>Tekanan</td>
                        <td>Tabung</td>
                        <td>Pin</td>
                        <td>Handle</td>
                        <td>Selang</td>
                        <td>Keterangan</td>
                        <td>Pemeriksa</td>
                    </thead>
                </tr>
                {% if pemeriksaan_list %}
                {% for cek in pemeriksaan_list %}
                <tr>
                    <td>{{ cek.tanggal }}</td>
                    <td>{{ cek.get_tekanan_display }}</td>
                    <td>{{ cek.get_tabung_display }}</td>
                    <td>{{ cek.get_pin_display }}</td>
                    <td>{{ cek.get_handle_display }}</td>
                    <td>{{ cek.get_selang_display }}</td>
                    <td>{{ cek.keterangan }}</td>
                    <td>{{ cek.pemeriksa }}</td>
                </tr>
                {% endfor %}
                {% endif %}
            </table>
        </div>
    </div>
</div>
<script>
    let nomor_apar = document.getElementById('id_nomor').value;
    function isiQR(){
        nomor_apar = document.getElementById('id_nomor').value;
        document.getElementById('id_path_QR').value = 'fln-apar-' + nomor_apar;
    }
    function isiSlug(){
        document.getElementById('id_slug').value = 'fln-apar-' + nomor_apar;
    }
    isiQR();
    isiSlug();
</script>
{% endblock content %}

templates/apar_updateview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    
</div>
<br>
<div class="container shadow px-4 p-4">
    <h2>Update Data APAR {{ object.nomor }}</h2>
    <div class="row">
        <div class="col p-3 text-center">
            <img src="{{ object.path_foto.url }}" max-width="100%" width="280px" height="390px" class="rounded">
        </div>
        <div class="col p-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-borderless">
                    <thead>
                    
                    </thead>
                    <tbody>
                        {% for field in form %}
                        <tr>
                            <td>
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% if field.field.required %}
                                    <span class="required">*</span>
                                {% endif %}
                            </td>
                            <td>
                                {{ field }}
                                {% if field.help_text %}
                                    <br><small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                                {% if field.name == 'path_QR' and form.path_QR.value %}
                                    <img src="{{ MEDIA_URL }}/media/images/qrcodes/{{ object.path_QR }}.png" alt="{{ form.path_QR.value }}" width="34">
                                {% endif %}
                            </td>
                          </tr>
                          {% if field.errors %}
                            <tr>
                              <td></td>
                              <td>
                                <div class="alert alert-danger">
                                  {% for error in field.errors %}
                                    <p>{{ error }}</p>
                                  {% endfor %}
                                </div>
                              </td>
                            </tr>
                          {% endif %}
                        {% endfor %}
                    </tbody>
                    <tr>
                        <th>
                           
                        </th>
                        <td class="text-end">
                            <button type="submit" class="btn btn-success">Save</button>
                            <a href="{% url 'DashboardHome' %}"  class="btn btn-danger">Cancel</a>
                        </td>
                    </tr>
                </table>
            
        </div>
        
        </form>
    </div>
</div>
<script>
    let nomor_apar = document.getElementById('id_nomor').value;
    function isiQR(){
        nomor_apar = document.getElementById('id_nomor').value;
        document.getElementById('id_path_QR').value = 'fln-apar-' + nomor_apar;
    }
    function isiSlug(){
        document.getElementById('id_slug').value = 'fln-apar-' + nomor_apar;
    }
    isiQR();
    isiSlug();
</script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Sistem Manajemen APAR</title>
</head>
<body>
    <!-- Menu navigasi mulai dari sini -->
    <nav class="navbar navbar-expand-lg navbar-light shadow-sm " >
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'scanner' %}"><img src="{% static 'images/fln_logo_small.png' %}" width="40" height="40""></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'DashboardHome' %}">List APAR</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Pemeriksaan APAR
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'cekapar' %}">Input Pemeriksaan APAR</a></li>
                  <li><a class="dropdown-item" href="{% url 'cekhistory' %}">Riwayat Pemeriksaan APAR</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'DashboardHome' %}">Report Pemeriksaan APAR</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Kelola APAR
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'createapar' %}">Tambah APAR</a></li>
                  <li><a class="dropdown-item" href="#">Status APAR</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'DashboardHome' %}">List APAR</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <!--a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a-->
                <a class="nav-link text-danger" href="{% url 'logout' %}">Logout ({{ user.username }})</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <!-- Menu navigasi sampai di sini -->
    <header>
        
    </header>
    <div class="container-fluid">
        {% block content %}
        {% endblock content %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
    $('#tableApar').DataTable( {
        "pageLength": 5

        } );
    } );
</script>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<div class="container p-4 card">
    <table id="tableApar" class="display"><!--class="table table-hover table-bordered align-middle"-->
        <thead class="" style="position:sticky;">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Lokasi</th>
                <th scope="col">Jenis</th>
                <th scope="col">Ukuran</th>
                <th scope="col">Expired</th>
                <th scope="col">Pemeriksaan Terakhir</th>
                <th scope="col">Foto di Lokasi</th>
                <th scope="col">Update?</th>
            </tr>
        </thead>
        <tbody>
        {% for apar in object_list %}
        <tr>
            <td>
                {{ apar.nomor }}
            </td>
            <td>
                <a href="{% url 'detailapar' %}{{ apar.slug }}">{{ apar.lokasi }}</a>
            </td>
            <td>
                {{ apar.jenis }}
            </td>
            <td>
                {{ apar.ukuran }} Kg
            </td>
            <td>
                {{ apar.expired }}
            </td>
            <td>
                {{ apar.tanggal_periksa }}
            </td>
            <td>
                <img src="media/{{ apar.path_foto }}" width="95" height="126">
            </td>
            <td>
                <a class="btn btn-primary" href="{% url 'updateapar' apar.id %}" >Update</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>

    </table>
</div>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
    $('#tableApar').DataTable( {
        "pageLength": 5
        } );
    } );
</script>
{% endblock content %}

templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Sistem Manajemen APAR</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>




    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">

    <main class="form-signin">
      <form method="post" action="{% url 'login' %}" novalidate>
        {% csrf_token %}
        <img class="mb-4" src="{% static 'images/fln_logo_small.png' %}" alt="">
        <h1 class="h3 mb-3 fw-normal">PT. Frina Lestari Nusantara <br> APAR Management System</h1>

        <div class="form-floating">
          <input type="email" class="form-control" id="id_username" placeholder="name@example.com" name="username">
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="id_password" placeholder="Password" name="password">
          <label for="floatingPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
          {% if form.errors %}
          <div class="alert alert-danger">
              Username atau Password kamu salah. Silahkan coba kembali.
          </div>
          {% endif %}
        </div>
        <input type="hidden" name="next" value="{{ next }}">
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
      </form>
    </main>
  </body>
</html>

templates/menu_scan.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row p-4">
    <div class="col-lg-4 d-flex flex-column align-items-center">
        <div class="card shadow" style="width: 20rem;">
            <img src="{{ apar.path_foto.url }}" class="card-img-top">
            <div class="card-body text-center">
                <h4>FLN APAR {{ object.nomor }}</h4>
                <h5>{{ object.nama }}</h5>
                <p class="card-text">{{ object.lokasi }}</p>
                <p><a class="w-100 btn btn-primary" href="{% url 'cekapar' %}{{ apar.slug }}">Cek Apar</a></p>
                <p><a class="w-100 btn btn-secondary" href="{% url 'detailapar' %}{{ apar.slug }}">History</a></p>
                
            </div>
        </div>
        
    </div>
</div>
<div class="row">
    <div class="col">

    </div>
</div>
<div class="row">
    <div class="col">
        
    </div>
</div>
{% endblock content %}

templates/pemeriksaan_createview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-borderless">
            {{ form.as_table }}
        </table>
    </form>
</div>
{% endblock content %}

templates/pemeriksaan_listview.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

<div class="table-fluid">
    <table class="table">
        <tr>
            <thead>
                <td>Tanggal Cek</td>
                <td>No. APAR / Lokasi</td>
                <td>Tekanan</td>
                <td>Tabung</td>
                <td>Pin</td>
                <td>Handle</td>
                <td>Selang</td>
                <td>Keterangan</td>
                <td>Pemeriksa</td>
            </thead>
        </tr>
        {% for cek in object_list %}
        <tr>
            <td>{{ cek.tanggal }}</td>
            <td>{{ cek.apar }}</td>
            <td>{{ cek.get_tekanan_display }}</td>
            <td>{{ cek.get_tabung_display }}</td>
            <td>{{ cek.get_pin_display }}</td>
            <td>{{ cek.get_handle_display }}</td>
            <td>{{ cek.get_selang_display }}</td>
            <td>{{ cek.keterangan }}</td>
            <td>{{ cek.pemeriksa }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

templates/pemeriksaanbyid_createview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid p-3">
    <h4 class="text-uppercase p-3 text-center">Input Pemeriksaan {{current_path}} </h4>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table table-borderles">
                {{ form.as_table }}
                <!--tr>
                    <th></th>
                    <td>
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Update Foto APAR
                        </button>
                    </td>
                </tr-->
                <tr>
                    <th></th>
                    <td class="text-end">
                        <button type="submit" class="btn btn-success">Save</button>
                        <a href="{% url 'scanmenu'  %}{{ current_path }}"  class="btn btn-danger">Cancel</a>
                    </td>
                </tr>
            </table>
        </div>
        <!-- Modal -->
        <!--div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update Foto APAR</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                ...
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
            </div>
        </div-->


    </form>
</div>
{% endblock content %}

templates/scan.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <div>
      <div class="bg-light p-5 rounded">
        <div class="col-sm-8 mx-auto">
          <h1>Sistem Management APAR</h1>
          <div>Welcome, {{ user.first_name }} {{ user.last_name }}</div>
          <div style="width: 220px" id="reader"></div>
          <div></div>
          <div style="width: 220px" id="reader-"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="row p-4">
    <div class="col-lg-4 d-flex flex-column align-items-center">
        <div class="card shadow" style="width: 20rem;">
            <img src="{{ apar.path_foto.url }}" class="card-img-top">
            <div class="card-body text-center">
                <h4>Sistem Management APAR</h4>
                <h6>-- Scan QR APAR --</h6>
                <p class="card-text"><div style="width: 280px" id="reader2"></div></p>
            </div>
        </div>
    </div>
  </div>

    <script src="{% static 'js/html5-qrcode.min.js' %}"></script>
    <script>
      function onScanSuccess(decodedText, decodedResult) {
        decodedResult = 'scan/' + decodedText;
        location.replace(decodedResult);
      }

      var html5QrcodeScanner = new Html5QrcodeScanner(
          "reader2", { fps: 10, qrbox: 180 });
      html5QrcodeScanner.render(onScanSuccess);
    </script>
    <script>
      var cameraId = 0;
      // This method will trigger user permissions
      Html5Qrcode.getCameras().then(devices => {
        /**
         * devices would be an array of objects of type:
         * { id: "id", label: "label" }
         */
        if (devices && devices.length) {
          cameraId = devices[0].id;
          // .. use this to start scanning.
          console.log(cameraId)
        } return cameraId;
      }).catch(err => {
        // handle err
        console.log(`Error scanning file. Reason: ${err}`)
      });

      //devices();
      console.log("cameraId: " + cameraId);
      const html5QrCode = new Html5Qrcode(/* element id */ "reader");
      html5QrCode.start(
        cameraId, 
        {
          fps: 10,    // Optional, frame per seconds for qr code scanning
          qrbox: { width: 250, height: 250 }  // Optional, if you want bounded box UI
        },
        (decodedText, decodedResult) => {
          // do something when code is read
        },
        (errorMessage) => {
          // parse error, ignore it.
        })
      .catch((err) => {
        // Start failed, handle it.
      });
    </script>
{% endblock content%}